### ISSUE TITLE
ORA-12899: value too large for column "KVR000"."KINNISTU_PIIRANGUD"."LIIK"

### ISSUE THREAD

**Issue by tormi** [kinnisvara/RKVR#7]
From: Kalev Repp [mailto:Kalev.Repp@mnt.ee] 
Sent: Tuesday, June 30, 2015 1:44 PM
To: Riigi kinnisvararegister
Subject: Kinnistu andmete uuenemine

Tere!

Soovin riigi kinnisvararegistris uuendada Kaopalu kruusakarjääri kinnistu, registriosa number 1252332, katastritunnus 77601:003:0035 andmeid, kuna jagamise katastriüksuse 3-ks. RKVR ei lase uuendada ning annab vea teate: 
ORA-12899: value too large for column "KVR000"."KINNISTU_PIIRANGUD"."LIIK" (actual: 32, maximum: 30)
Palun Teie abi.

Lugupidamisega,
Kalev Repp
Maanteeamet 
Teemaa osakond
maakorraldaja
telef. 443 5695
Kalev Repp kalev.repp@mnt.ee

**Comment by tormi** [comment]
Vea parandamine on töös:

From: Villem Vannas [mailto:Villem.Vannas@datel.ee] 
Sent: Thursday, July 02, 2015 10:33 AM
Subject: RE: Kinnistu andmete uuenemine

Tere,

Justiits on uusi piirangute liike lisanud, mis ei mahu enam KVR varasema pikkusega andmebaasi andmeväljale ära, seega on vajalik teha täiendus ehk siis suurendada andmevälja pikkust. Lisatud on andmebaasi skript, mis seda teeb. Palun käivitada nii KVR testi- kui tootekeskkonnas.

Tervitades,
Villem Vannas

**Comment by KatrinSolvak** [comment]
Lahendatud 13.07.2015
